name: metornome
description: "."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  cupertino_icons: ^1.0.8
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  flutter_riverpod: ^2.0.0
  go_router: ^14.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
