name: metornome
description: "."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  cupertino_icons: ^1.0.8
  drift: ^2.21.0
  flutter_riverpod: ^2.0.0
  go_router: ^14.6.1
  path_provider: ^2.1.5
  path: ^1.9.0
  google_fonts: ^6.2.1

dev_dependencies:
  drift_dev: ^2.0.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-Regular.ttf
        - asset: assets/fonts/Exo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/Exo2-Italic.ttf
          style: italic
  assets:
    - assets/sounds/
